version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
  prod:
    build: .
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: bundle exec puma -C config/puma.rb
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - prod
volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  db-data:
